name: webtop-os

services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: webtop
    security_opt:
      - seccomp:unconfined # optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SUBFOLDER=/ # optional
      - TITLE=Webtop # optional
      - SUDO_PASSWORD=toor
      - PASSWORD=toor
      - CUSTOM_USER=webtop
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:code-server-zsh
      - INSTALL_PACKAGES=unzip|chromium|nano|neovim|git|htop|curl|wget|ripgrep|fonts-lyx|xclip|xsel|gcc|clang|build-essential|libgtk-4-1|libgraphene-1.0-0|libxslt1.1|libwoff1|libevent-2.1-7|libgstreamer-gl1.0-0|libgstreamer-plugins-bad1.0-0|libharfbuzz-icu0|libsecret-1-0|libhyphen0|libmanette-0.2-0|libgles2|x11-xserver-utils|xorg|x11-common|x11-utils
    volumes:
      - /home/kdlocpanda/all_the_docks/webtop-os/webtop-config:/config:rw
      - /home/kdlocpanda/all_the_docks/webtop-os/webtop-inject-scripts:/custom-cont-init.d:rw
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri # optional
    shm_size: "4gb" # optional
    restart: unless-stopped
    privileged: true # Enable privileged mode for DinD
