apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: webtop-config
  name: webtop-config
  namespace: webtop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
