apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c --volumes persistentVolumeClaim --controller deployment --namespace webtop --pvc-request-size 10Gi --with-kompose-annotation -v
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: webtop
  name: webtop
  namespace: webtop
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: webtop
